name: Update sub-web

on:
  workflow_dispatch:

concurrency: 
  group: sub-web
  # 自动取消其他运行中的workflow
  cancel-in-progress: true 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Update sub-web
      run: |
        git clone https://github.com/CareyWang/sub-web.git
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get dependencies and build
      run: |
        cd sub-web
        yarn install
        yarn build
        
    - name: Clean up
      run: |
        cd $GITHUB_WORKSPACE
        sudo rm -rf files/dist
        sudo cp -rf sub-web/dist files/
        sudo rm -rf sub-web
        
    - name: Add & Commit
      uses: EndBug/add-and-commit@v6
      with:
        author_name: GitHub Action
        author_email: noreply@github.com
        message: "Update sub-web"
        add: "-A"
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
